# Liability raises draw chance; these effects are worldly but never label an oath.

[[cards]]
id = "oil_store_fire"
weight = 5
liability_weight = 3
good = "oil"
loss = 240
legitimacy_delta = 0
unrest_delta = 10

[[cards]]
id = "palace_illness"
weight = 4
liability_weight = 4
good = ""
loss = 0
legitimacy_delta = -20
unrest_delta = 0

[[cards]]
id = "bad_omens"
weight = 3
liability_weight = 5
good = ""
loss = 0
legitimacy_delta = -10
unrest_delta = 20
